### ISSUE TITLE
Parsing error: Unexpected token =>

### ISSUE THREAD

**Issue by aifeelit** [aifeelit/firebase-auth-magic-link#1]
Encounted an error while deploying cloud functions to firebase

**Comment by aifeelit** [comment]
https://magic.link/posts/magic-firebase-integration

**Comment by aifeelit** [comment]
Figured that out!

![image](https://user-images.githubusercontent.com/14981215/172764686-e08bae2d-0de4-44ae-8bd7-eaabb08f3cd0.png)

removed that damn dot (.)

**Comment by Anthony-3** [comment]
Thanks, @aifeelit
Very helpful

**Comment by ted3m** [comment]
Would you share the versions you use?

**Comment by aifeelit** [comment]
https://github.com/aifeelit/firebase-magic-link-auth/blob/master/functions/package.json

**Comment by aifeelit** [comment]
Oopss. sorry
this one

https://github.com/aifeelit/firebase-auth-magic-link/blob/master/functions/package.json

**Comment by edrdm** [comment]
AWESOME!
just wondering firebase init function made such issue on package.json 🙄
